name: Validate, Build & maybe Deploy

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & maybe Push Container
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: ${{ github.ref_name == 'main' }}
        tags: |
            ghcr.io/srobo/discord-gated-entry:build-${{ github.run_number }}
            ghcr.io/srobo/discord-gated-entry:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
