name: Validate, Build & maybe Deploy

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
