name: Validate, Build & maybe Deploy

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build & maybe Push Container
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: ${{ github.ref_name == '16/merge' }}
        tags: |
            srobo/discord-gated-entry:build-${{ github.run_number }}
            srobo/discord-gated-entry:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
